name: login
description: Simple Firebase Login

version: 1.0.0+2

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  firebase_core: ^2.15.1
  firebase_analytics: ^10.4.5
  firebase_auth: ^4.8.0
  ionicons: ^0.2.2
  video_player: ^2.2.19
  lottie: ^3.1.0
  animate_do: ^2.0.0
  smooth_page_indicator: ^1.1.0
  nb_utils: ^6.1.0
  dots_indicator: ^2.0.0
  flutter_svg: ^0.23.0+1
  url_launcher: ^6.0.12
  cached_network_image: ^3.1.0
  flutter_staggered_grid_view: ^0.4.1
  html: ^0.15.0
  intl: ^0.17.0
  connectivity_plus_web: ^1.2.5 

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/animations/
    
  

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 500

        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700

        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 300