name: login
description: Simple Firebase Login

version: 1.0.0+2

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  firebase_core: ^2.15.1
  firebase_analytics: ^10.4.5
  firebase_auth: ^4.8.0
  ionicons: ^0.2.2
  video_player: ^2.2.19

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
  

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 500

        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700

        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 300